services:
  - name: data-hunt
    type: web
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: data_hunt_production
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: data_hunt_production
          type: redis
          property: connectionString
  - name: data_hunt_production
    type: redis
    ipAllowList: []
databases:
  - name: data_hunt_production
    ipAllowList: []
